package br.com.poimen.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MinistryMembershipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMinistryMembershipAllPropertiesEquals(MinistryMembership expected, MinistryMembership actual) {
        assertMinistryMembershipAutoGeneratedPropertiesEquals(expected, actual);
        assertMinistryMembershipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMinistryMembershipAllUpdatablePropertiesEquals(MinistryMembership expected, MinistryMembership actual) {
        assertMinistryMembershipUpdatableFieldsEquals(expected, actual);
        assertMinistryMembershipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMinistryMembershipAutoGeneratedPropertiesEquals(MinistryMembership expected, MinistryMembership actual) {
        assertThat(expected)
            .as("Verify MinistryMembership auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMinistryMembershipUpdatableFieldsEquals(MinistryMembership expected, MinistryMembership actual) {
        assertThat(expected)
            .as("Verify MinistryMembership relevant properties")
            .satisfies(e -> assertThat(e.getRole()).as("check role").isEqualTo(actual.getRole()))
            .satisfies(e -> assertThat(e.getStartDate()).as("check startDate").isEqualTo(actual.getStartDate()))
            .satisfies(e -> assertThat(e.getEndDate()).as("check endDate").isEqualTo(actual.getEndDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMinistryMembershipUpdatableRelationshipsEquals(MinistryMembership expected, MinistryMembership actual) {
        assertThat(expected)
            .as("Verify MinistryMembership relationships")
            .satisfies(e -> assertThat(e.getMinistryGroup()).as("check ministryGroup").isEqualTo(actual.getMinistryGroup()))
            .satisfies(e -> assertThat(e.getMember()).as("check member").isEqualTo(actual.getMember()));
    }
}
